Repository jupyter/jupyter-packaging, pull requests merged in 2021-05, with the labels that each got.

#84 Add more options to Build
  README.md
  jupyter_packaging/build_api.py
  jupyter_packaging/setupbase.py
  tests/conftest.py
  tests/test_build_api.py
  tests/test_install.py
Labels: enhancement

#85 Update Changelog for 0.10
  CHANGELOG.md
Labels: documentation

#86 Fix Handling of Skip If Exists
  jupyter_packaging/setupbase.py
Labels: bug

#87 Update changelog for 0.10.1
  CHANGELOG.md
Labels: documentation

#89 Deprecate `get_version_info` and recommend against runtime dependency
  README.md
  jupyter_packaging/setupbase.py
  tests/test_deprecated.py
  tests/test_utility_functions.py
Labels: maintenance

#90 Fix Handling of npm Parameter
  jupyter_packaging/setupbase.py
Labels: bug

#91 Update changelog for 0.10.2
  CHANGELOG.md
Labels: documentation
