Repository jupyter/jupyter-packaging, pull requests merged in 2022-03, with the labels that each got.

#129 Add source URL to pypi project page
  setup.cfg
Labels: maintenance

#131 Update import for new setuptools path (setuptools >=61.0.0)
  jupyter_packaging/setupbase.py
Labels: bug

#132 Automated Changelog Entry for 0.12.0 on main
  CHANGELOG.md
Labels: documentation

#133 Allow skipping npm with JUPYTER_PACKAGING_SKIP_NPM env
  jupyter_packaging/setupbase.py
Labels: enhancement

#137 Clean up CI and Tests
  .github/workflows/check-release.yml
  .github/workflows/main.yml
  .pre-commit-config.yaml
  jupyter_packaging/__init__.py
  jupyter_packaging/build_api.py
  jupyter_packaging/setupbase.py
  pyproject.toml
  setup.cfg
  tests/conftest.py
  tests/test_build_api.py
  tests/test_datafiles_install.py
  tests/test_deprecated.py
  tests/test_install.py
  tests/test_utility_functions.py
Labels: maintenance

#139 Update pre-commit
  .pre-commit-config.yaml
Labels: maintenance
